# create Event object from GND endpoint
[[filters]]
"rdf:type" = "gndo:HistoricSingleEventOrEra"

[[filters]]
"rdf:type" = "gndo:ConferenceOrEvent"

[attributes]
label = ["gndo:preferredNameForTheSubjectHeading", "gndo:preferredNameForTheConferenceOrEvent", "gndo:dateOfEstablishment"]
date_range = ["gndo:dateOfProduction", "gndo:dateOfConferenceOrEvent"]
sameas = "owl:sameAs"
