# create Work object from GND endpoint
[[filters]]
"rdf:type" = "gndo:Work"

[attributes]
title = ["gndo:preferredNameForTheWork"]
sameas = "owl:sameAs"

[relations]
"apis_ontology.personisauthorofwork" = { curies = "gndo:firstAuthor", subj = "apis_ontology.person" }
