# Generated by Django 5.1.3 on 2024-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0011_alter_event_options_alter_versionevent_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
    ]
