# Generated by Django 5.1.3 on 2024-12-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0012_alter_poster_label_alter_versionposter_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
    ]
