# Generated by Django 5.1.3 on 2024-12-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0013_poster_height_poster_notes_poster_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Titel"
            ),
        ),
    ]
