# Generated by Django 5.1.3 on 2024-12-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0013_alter_event_label_alter_versionevent_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="Länge"),
        ),
        migrations.AddField(
            model_name="poster",
            name="notes",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Anmerkungen"
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Anzahl"
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="status",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Status"
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="storage_location",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Archivierung"
            ),
        ),
        migrations.AddField(
            model_name="poster",
            name="width",
            field=models.FloatField(blank=True, null=True, verbose_name="Breite"),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="Länge"),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="notes",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Anmerkungen"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="quantity",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Anzahl"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="status",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Status"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="storage_location",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="Archivierung"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="width",
            field=models.FloatField(blank=True, null=True, verbose_name="Breite"),
        ),
    ]
