# Generated by Django 5.1.4 on 2024-12-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0015_performance_versionperformance"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "Ausstellung"),
                    ("Buchpräsentation", "Buchpräsentation"),
                    ("Konferenz", "Konferenz"),
                    ("Lesung", "Lesung"),
                    ("Videovorführung", "Videovorführung"),
                    ("Vortrag", "Vortrag"),
                ],
                default="",
                max_length=1024,
                verbose_name="Eventtyp",
            ),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "Ausstellung"),
                    ("Buchpräsentation", "Buchpräsentation"),
                    ("Konferenz", "Konferenz"),
                    ("Lesung", "Lesung"),
                    ("Videovorführung", "Videovorführung"),
                    ("Vortrag", "Vortrag"),
                ],
                default="",
                max_length=1024,
                verbose_name="Eventtyp",
            ),
        ),
    ]
