# Generated by Django 5.1.4 on 2024-12-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0017_eventhadparticipantgroup_eventhadparticipantperson_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "Ausstellung"),
                    ("Buchpräsentation", "Buchpräsentation"),
                    ("Konferenz", "Konferenz"),
                    ("Lesung", "Lesung"),
                    ("Videovorführung", "Videovorführung"),
                    ("Vortrag", "Vortrag"),
                ],
                default="",
                max_length=1024,
                verbose_name="Veranstaltungstyp",
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "Ausstellung"),
                    ("Buchpräsentation", "Buchpräsentation"),
                    ("Konferenz", "Konferenz"),
                    ("Lesung", "Lesung"),
                    ("Videovorführung", "Videovorführung"),
                    ("Vortrag", "Vortrag"),
                ],
                default="",
                max_length=1024,
                verbose_name="Veranstaltungstyp",
            ),
        ),
    ]
