# Generated by Django 5.1.4 on 2024-12-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0018_alter_event_event_type_alter_versionevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="notes",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="Anmerkungen"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="notes",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="Anmerkungen"
            ),
        ),
    ]
