# Generated by Django 5.1.4 on 2025-01-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0019_alter_poster_notes_alter_versionposter_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="Land"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="Land"
            ),
        ),
    ]
