# Generated by Django 5.1.4 on 2025-01-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0020_poster_country_versionposter_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="year",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Jahr"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="year",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="Jahr"
            ),
        ),
    ]
