# Generated by Django 5.1.4 on 2025-03-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0021_poster_year_versionposter_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionevent",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versiongroup",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionitem",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionmanifestation",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionperformance",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionposter",
            name="self_contenttype",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="self_contenttype",
        ),
        migrations.AddField(
            model_name="place",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
            ),
        ),
    ]
