# Generated by Django 5.1.4 on 2025-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0022_remove_versionevent_self_contenttype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Anzahl"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Anzahl"),
        ),
    ]
