# Generated by Django 5.1.4 on 2025-03-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0023_alter_poster_quantity_alter_versionposter_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="poster",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Signatur"
            ),
        ),
        migrations.AddField(
            model_name="versionposter",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Signatur"
            ),
        ),
    ]
