# Generated by Django 5.1.4 on 2025-03-17 13:45

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0024_poster_signature_versionposter_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="performance",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Eingabe in der Form: "ab YYYY-MM-DD bis YYYY-MM-DD", wobei beide Datumsteile optional sind und auch unvollständige Daten angegeben werden können. Bsp: ab 1982-02 bis 1982-03',
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AddField(
            model_name="performance",
            name="date_range_date_from",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="performance",
            name="date_range_date_sort",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="performance",
            name="date_range_date_to",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Eingabe in der Form: "ab YYYY-MM-DD bis YYYY-MM-DD", wobei beide Datumsteile optional sind und auch unvollständige Daten angegeben werden können. Bsp: ab 1982-02 bis 1982-03',
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="date_range_date_from",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="date_range_date_sort",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="versionperformance",
            name="date_range_date_to",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
