# Generated by Django 5.1.4 on 2025-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0026_event_date_range_event_date_range_date_from_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_range_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_range_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_range_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="date_range_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="date_range_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="date_range_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="person",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="date of death"),
        ),
        migrations.AlterField(
            model_name="person",
            name="forename",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="forename"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="gender"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="surname",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="surname"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="date_range_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="date_range_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="date_range_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongroup",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="date_range_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="date_range_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="date_range_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="date_of_death",
            field=models.DateField(blank=True, null=True, verbose_name="date of death"),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="forename",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="forename"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="gender",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="gender"
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="surname",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="surname"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="latitude"),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="longitude"),
        ),
    ]
