# Generated by Django 5.1.4 on 2025-05-12 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0027_alter_event_date_range_date_from_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["label"],
                "verbose_name": "Körperschaft",
                "verbose_name_plural": "Körperschaften",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["surname", "forename"],
                "verbose_name": "Person",
                "verbose_name_plural": "Personen",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["label"],
                "verbose_name": "Ort",
                "verbose_name_plural": "Orte",
            },
        ),
    ]
