# Generated by Django 5.1.4 on 2025-05-12 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0028_alter_group_options_alter_person_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["label"],
                "verbose_name": "Veranstaltung",
                "verbose_name_plural": "Veranstaltungen",
            },
        ),
        migrations.AlterModelOptions(
            name="eventhadparticipantgroup",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="eventhadparticipantperson",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="eventwasmotivatedbywork",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={
                "ordering": ["title"],
                "verbose_name": "Expression",
                "verbose_name_plural": "Expressionen",
            },
        ),
        migrations.AlterModelOptions(
            name="groupispublisherofmanifestation",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["title"],
                "verbose_name": "Exemplar",
                "verbose_name_plural": "Exemplare",
            },
        ),
        migrations.AlterModelOptions(
            name="itemexemplifiesmanifestation",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="manifestation",
            options={
                "ordering": ["title"],
                "verbose_name": "Manifestation",
                "verbose_name_plural": "Manifestationen",
            },
        ),
        migrations.AlterModelOptions(
            name="manifestationembodiesexpression",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="performance",
            options={
                "ordering": ["label"],
                "verbose_name": "Aufführung",
                "verbose_name_plural": "Aufführungen",
            },
        ),
        migrations.AlterModelOptions(
            name="performancehaddirectorperson",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="performancehadparticipantgroup",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="performancehadparticipantperson",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="performanceperformedwork",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="personisauthorofwork",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="poster",
            options={
                "ordering": ["label"],
                "verbose_name": "Plakat",
                "verbose_name_plural": "Plakate",
            },
        ),
        migrations.AlterModelOptions(
            name="posterpromotedevent",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="posterpromotedperformance",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["title"],
                "verbose_name": "Werk",
                "verbose_name_plural": "Werke",
            },
        ),
        migrations.AlterModelOptions(
            name="workisrealisedinexpression",
            options={"ordering": ["id"]},
        ),
    ]
