# Generated by Django 5.1.4 on 2025-05-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0029_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="Bezeichnung"
            ),
        ),
    ]
