# Generated by Django 5.1.4 on 2025-05-19 08:23

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0030_alter_event_label_alter_performance_label_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["label"],
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={
                "ordering": ["title"],
                "verbose_name": "expression",
                "verbose_name_plural": "expressions",
            },
        ),
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["label"],
                "verbose_name": "group",
                "verbose_name_plural": "groups",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["title"],
                "verbose_name": "item",
                "verbose_name_plural": "items",
            },
        ),
        migrations.AlterModelOptions(
            name="manifestation",
            options={
                "ordering": ["title"],
                "verbose_name": "manifestation",
                "verbose_name_plural": "manifestations",
            },
        ),
        migrations.AlterModelOptions(
            name="performance",
            options={
                "ordering": ["label"],
                "verbose_name": "performance",
                "verbose_name_plural": "performances",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["surname", "forename"],
                "verbose_name": "person",
                "verbose_name_plural": "persons",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["label"],
                "verbose_name": "place",
                "verbose_name_plural": "places",
            },
        ),
        migrations.AlterModelOptions(
            name="poster",
            options={
                "ordering": ["label"],
                "verbose_name": "poster",
                "verbose_name_plural": "posters",
            },
        ),
        migrations.AlterModelOptions(
            name="versionevent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical event",
                "verbose_name_plural": "historical events",
            },
        ),
        migrations.AlterModelOptions(
            name="versionexpression",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical expression",
                "verbose_name_plural": "historical expressions",
            },
        ),
        migrations.AlterModelOptions(
            name="versiongroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical group",
                "verbose_name_plural": "historical groups",
            },
        ),
        migrations.AlterModelOptions(
            name="versionitem",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical item",
                "verbose_name_plural": "historical items",
            },
        ),
        migrations.AlterModelOptions(
            name="versionmanifestation",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical manifestation",
                "verbose_name_plural": "historical manifestations",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperformance",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical performance",
                "verbose_name_plural": "historical performances",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place",
                "verbose_name_plural": "historical places",
            },
        ),
        migrations.AlterModelOptions(
            name="versionposter",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical poster",
                "verbose_name_plural": "historical posters",
            },
        ),
        migrations.AlterModelOptions(
            name="versionwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work",
                "verbose_name_plural": "historical works",
            },
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["title"],
                "verbose_name": "work",
                "verbose_name_plural": "works",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Input has to be formatted "ab YYYY-MM-DD bis YYYY-MM-DD" for from and to date, though either date is optional and dates may also remain incomplete. Ex. ab 1982-02 bis 1982-03',
                verbose_name="date range",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "exhibition"),
                    ("Buchpräsentation", "book presentation"),
                    ("Konferenz", "conference"),
                    ("Lesung", "book reading"),
                    ("Videovorführung", "screening"),
                    ("Vortrag", "lecture"),
                ],
                default="",
                max_length=1024,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Input has to be formatted "ab YYYY-MM-DD bis YYYY-MM-DD" for from and to date, though either date is optional and dates may also remain incomplete. Ex. ab 1982-02 bis 1982-03',
                verbose_name="date range",
            ),
        ),
        migrations.AlterField(
            model_name="performance",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="length"),
        ),
        migrations.AlterField(
            model_name="poster",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="notes",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="notes"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="poster",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="signature"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="status",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="storage_location",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="storage location"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="width",
            field=models.FloatField(blank=True, null=True, verbose_name="width"),
        ),
        migrations.AlterField(
            model_name="poster",
            name="year",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="year"
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Input has to be formatted "ab YYYY-MM-DD bis YYYY-MM-DD" for from and to date, though either date is optional and dates may also remain incomplete. Ex. ab 1982-02 bis 1982-03',
                verbose_name="date range",
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="event_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ausstellung", "exhibition"),
                    ("Buchpräsentation", "book presentation"),
                    ("Konferenz", "conference"),
                    ("Lesung", "book reading"),
                    ("Videovorführung", "screening"),
                    ("Vortrag", "lecture"),
                ],
                default="",
                max_length=1024,
                verbose_name="event type",
            ),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionitem",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionitem",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="date_range",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                default="",
                help_text='Input has to be formatted "ab YYYY-MM-DD bis YYYY-MM-DD" for from and to date, though either date is optional and dates may also remain incomplete. Ex. ab 1982-02 bis 1982-03',
                verbose_name="date range",
            ),
        ),
        migrations.AlterField(
            model_name="versionperformance",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="country",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="country"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="length"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="label",
            field=models.CharField(
                blank=True, default="", max_length=4096, verbose_name="label"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="notes",
            field=models.TextField(
                blank=True, default="", max_length=1024, verbose_name="notes"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="signature",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="signature"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="status",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="status"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="storage_location",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="storage location"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="width",
            field=models.FloatField(blank=True, null=True, verbose_name="width"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="year",
            field=models.CharField(
                blank=True, default="", max_length=4, verbose_name="year"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="title"
            ),
        ),
    ]
