# Generated by Django 5.1.4 on 2025-05-28 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0031_alter_event_options_alter_expression_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionevent",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versioneventhadparticipantgroup",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versioneventhadparticipantperson",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versioneventwasmotivatedbywork",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versiongroup",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versiongroupispublisherofmanifestation",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionitem",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionitemexemplifiesmanifestation",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionmanifestation",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionmanifestationembodiesexpression",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperformance",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperformancehaddirectorperson",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperformancehadparticipantgroup",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperformancehadparticipantperson",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperformanceperformedwork",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionperson",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionpersonisauthorofwork",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionplace",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionposter",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionposterpromotedevent",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionposterpromotedperformance",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionwork",
            name="version_tag",
        ),
        migrations.RemoveField(
            model_name="versionworkisrealisedinexpression",
            name="version_tag",
        ),
    ]
