# Generated by Django 5.2.3 on 2025-07-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0033_alter_versioneventhadparticipantgroup_obj_object_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="versionitem",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="other title information",
            ),
        ),
    ]
