# Generated by Django 5.2.3 on 2025-07-09 19:28

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0034_expression_other_title_information_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifestation",
            name="isbn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use hyphens or spaces to separate the individual parts of the ISBN or enter it as one continuous sequence. Ex. 978-3-518-06505-1",
                max_length=17,
                verbose_name="ISBN",
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="publication_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                help_text="Can be a full or partial date and also accepts (partial) date ranges to cover uncertain or unclear dates. A full date may be entered in DD.MM.YYYY or YYYY-MM-DD format, a partial date can be a full year YYYY or may otherwise be formatted MM.YYYY or YYYY-MM. Date ranges need to entered with keywords 'ab' ('from') and 'bis' ('to') to mark their (exact or approximate) start and end dates. Ex. 1989. Ex. 1971-05. Ex. ab 1990-03-26 bis 1990-03-27.",
                null=True,
                verbose_name="publication date",
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="publication_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="publication_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="publication_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="manifestation",
            name="relevant_pages",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use semicolons to separate multiple pages or page ranges from one another. Ex. 7; 31-42; 185-210",
                max_length=255,
                verbose_name="relevant pages",
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="isbn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use hyphens or spaces to separate the individual parts of the ISBN or enter it as one continuous sequence. Ex. 978-3-518-06505-1",
                max_length=17,
                verbose_name="ISBN",
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="publication_date",
            field=django_interval.fields.FuzzyDateParserField(
                blank=True,
                help_text="Can be a full or partial date and also accepts (partial) date ranges to cover uncertain or unclear dates. A full date may be entered in DD.MM.YYYY or YYYY-MM-DD format, a partial date can be a full year YYYY or may otherwise be formatted MM.YYYY or YYYY-MM. Date ranges need to entered with keywords 'ab' ('from') and 'bis' ('to') to mark their (exact or approximate) start and end dates. Ex. 1989. Ex. 1971-05. Ex. ab 1990-03-26 bis 1990-03-27.",
                null=True,
                verbose_name="publication date",
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="publication_date_date_from",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="publication_date_date_sort",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="publication_date_date_to",
            field=models.DateField(
                auto_created=True, blank=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="relevant_pages",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use semicolons to separate multiple pages or page ranges from one another. Ex. 7; 31-42; 185-210",
                max_length=255,
                verbose_name="relevant pages",
            ),
        ),
    ]
