# Generated by Django 5.2.3 on 2025-07-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0035_manifestation_isbn_manifestation_publication_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="versionwork",
            name="tbit_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Romane", "prose: novels"),
                    ("Novellen", "prose: novellas & short prose"),
                    ("Autobiografie", "prose: autobiography"),
                    ("Drama", "drama & libretti"),
                    ("Lyrik", "poetry"),
                    (
                        "Sonstiges",
                        "other: letters, speeches, interviews & other writings",
                    ),
                    ("Adaptionen", "adaptations"),
                    ("Fragmente", "fragments"),
                ],
                default="",
                help_text='Used by "Thomas Bernhard in translation" to group works by genre and/or type.',
                max_length=1024,
                verbose_name='"TB in translation" category',
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="tbit_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Romane", "prose: novels"),
                    ("Novellen", "prose: novellas & short prose"),
                    ("Autobiografie", "prose: autobiography"),
                    ("Drama", "drama & libretti"),
                    ("Lyrik", "poetry"),
                    (
                        "Sonstiges",
                        "other: letters, speeches, interviews & other writings",
                    ),
                    ("Adaptionen", "adaptations"),
                    ("Fragmente", "fragments"),
                ],
                default="",
                help_text='Used by "Thomas Bernhard in translation" to group works by genre and/or type.',
                max_length=1024,
                verbose_name='"TB in translation" category',
            ),
        ),
    ]
