# Generated by Django 5.2.3 on 2025-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0036_versionwork_tbit_category_work_tbit_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifestation",
            name="tbit_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Identifier for "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name='TBit "signatur"',
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="tbit_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Identifier for "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name='TBit "signatur"',
            ),
        ),
    ]
