# Generated by Django 5.2.3 on 2025-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0038_itemhaskeepergroup_versionitemhaskeepergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="language"
            ),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=5, verbose_name="language"
            ),
        ),
    ]
