# Generated by Django 5.2.3 on 2025-08-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0039_expression_language_versionexpression_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manifestation",
            name="tbit_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Identifier used for "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name="TBit ID",
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="tbit_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Identifier used for "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name="TBit ID",
            ),
        ),
    ]
