# Generated by Django 5.2.3 on 2025-08-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0040_alter_manifestation_tbit_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifestation",
            name="tbit_shelfmark",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Shelfmark of "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name="TBit shelfmark",
            ),
        ),
        migrations.AddField(
            model_name="versionmanifestation",
            name="tbit_shelfmark",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Shelfmark of "Thomas Bernhard in translation" publications',
                max_length=50,
                verbose_name="TBit shelfmark",
            ),
        ),
    ]
