# Generated by Django 5.2.6 on 2025-10-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0042_alter_place_feature_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionitem",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="versionitem",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionitem",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="other_title_information",
            field=models.CharField(
                blank=True,
                default="",
                max_length=1024,
                verbose_name="other title information",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="subtitle",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="title"
            ),
        ),
    ]
