# Generated by Django 5.2.6 on 2025-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0043_alter_expression_other_title_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expression",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="language"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="language",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="language"
            ),
        ),
    ]
