# Generated by Django 5.2.6 on 2025-10-24 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0044_alter_expression_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manifestation",
            name="tbit_id",
        ),
        migrations.RemoveField(
            model_name="versionmanifestation",
            name="tbit_id",
        ),
    ]
