# Generated by Django 5.2.6 on 2025-12-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0046_personistranslatorofexpression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="height"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="height"),
        ),
    ]
