# Generated by Django 5.2.6 on 2025-12-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0047_alter_poster_height_alter_versionposter_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="height",
            field=models.FloatField(
                blank=True, help_text="unit: mm", null=True, verbose_name="height"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="width",
            field=models.FloatField(
                blank=True, help_text="unit: mm", null=True, verbose_name="width"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="height",
            field=models.FloatField(
                blank=True, help_text="unit: mm", null=True, verbose_name="height"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="width",
            field=models.FloatField(
                blank=True, help_text="unit: mm", null=True, verbose_name="width"
            ),
        ),
    ]
