# Generated by Django 5.2.6 on 2026-01-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0048_alter_poster_height_alter_poster_width_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="height",
            field=models.IntegerField(
                blank=True, help_text="unit: mm", null=True, verbose_name="height"
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="width",
            field=models.IntegerField(
                blank=True, help_text="unit: mm", null=True, verbose_name="width"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="height",
            field=models.IntegerField(
                blank=True, help_text="unit: mm", null=True, verbose_name="height"
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="width",
            field=models.IntegerField(
                blank=True, help_text="unit: mm", null=True, verbose_name="width"
            ),
        ),
    ]
