# Generated by Django 6.1 on 2026-08-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0050_manifestation_primary_language_manifestation_variety_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="quantity"),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="quantity"),
        ),
    ]
