# Generated by Django 6.1 on 2026-09-02 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0053_expression_primary_language_expression_variety_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expression",
            name="language",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="language",
        ),
    ]
