# Generated by Django 6.1 on 2026-09-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0054_remove_expression_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expression",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.RenameField(
            model_name="manifestation",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.RenameField(
            model_name="poster",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.RenameField(
            model_name="versionexpression",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.RenameField(
            model_name="versionmanifestation",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.RenameField(
            model_name="versionposter",
            old_name="variety",
            new_name="language_variety",
        ),
        migrations.AlterField(
            model_name="expression",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
        migrations.AlterField(
            model_name="manifestation",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
        migrations.AlterField(
            model_name="poster",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
        migrations.AlterField(
            model_name="versionmanifestation",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
        migrations.AlterField(
            model_name="versionposter",
            name="language_variety",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Brazil"),
                    ("PT", "Portugal"),
                    ("Hans", "Han simplified"),
                    ("Hant", "Han traditional"),
                ],
                default="",
                help_text="Regional variant, dialect or script type. Available options depend on the language selected.",
                max_length=4,
                verbose_name="language variety",
            ),
        ),
    ]
