name: Deploy TB online app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/deploy-apis-instance.yml@v0.6.0
    secrets: inherit
