# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

name: Run djLint linter

on:
  # runs when activity type is one of: opened, synchronize, reopened
  pull_request:
    paths:
      - "**.html"
  workflow_dispatch:

jobs:
  djlint-linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install default dependencies
        run: uv sync

      - name: Run djlint with --lint
        run: uv run djlint . --lint
