# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

name: Run djLint linter

on:
  # runs when activity type is one of: opened, synchronize, reopened
  pull_request:
  workflow_dispatch:

jobs:
  djlint-formatter:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/poetry-djlint.yml@v0.4.7
    with:
      src: "."
      options: "--lint"
