# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

name: Lint Git commit messages

on:
  pull_request:

jobs:
  gitlint:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/gitlint.yml@v0.6.0
    with:
      basebranch: ${{ github.event.repository.default_branch }}
