# SPDX-FileCopyrightText: 2024 K Kollmann
# SPDX-License-Identifier: MIT

name: Run Ruff formatter

on:
  # runs on opened, synchronised, reopened PRs
  pull_request:
    paths:
      - "**.py"
  workflow_dispatch:

jobs:
  ruff-formatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Install only dependencies for formatting/linting
        run: uv sync --only-group lint

      - name: Run ruff format
        run: uv run --no-sync ruff format --check
